from enum import Enum
MIN_CONFIDENCE = 0.50

class EvaluationReason(Enum):
    OK = "OK"
    NOT_VISIBLE = "NOT_VISIBLE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    INSUFFICIENT_KEYPOINTS = "INSUFFICIENT_KEYPOINTS"
    INVALID_MEASUREMENT = "INVALID_MEASUREMENT"